export type BlockCategory = 'Holz' | 'Stein & Erden' | 'Erze & Edelsteine' | 'Natur & Pflanzen' | 'Nether' | 'End' | 'Sonstiges'

export type BlockEntry = {
  id: string         // Minecraft block_type wie vom Plugin gespeichert, z.B. 'OAK_LOG'
  name: string         // Deutscher Anzeigename
  group: string        // Materialgruppe innerhalb der Kategorie, z.B. 'Eiche'
  category: BlockCategory
}

export const ALL_BLOCKS: BlockEntry[] = [
  // ===================== HOLZ =====================
  // --- Eiche ---
  { id: 'OAK_LOG', name: 'Eichenstamm', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_WOOD', name: 'Eichenholz', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_PLANKS', name: 'Eichenbretter', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_LEAVES', name: 'Eichenlaub', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_SAPLING', name: 'Eichensetzling', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_STAIRS', name: 'Eichentreppe', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_SLAB', name: 'Eichenstufe', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_FENCE', name: 'Eichenzaun', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_FENCE_GATE', name: 'Eichenzauntor', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_DOOR', name: 'Eichentür', group: 'Eiche', category: 'Holz' },
  { id: 'OAK_TRAPDOOR', name: 'Eichenfalltür', group: 'Eiche', category: 'Holz' },
  // --- Birke ---
  { id: 'BIRCH_LOG', name: 'Birkenstamm', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_WOOD', name: 'Birkenholz', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_PLANKS', name: 'Birkenbretter', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_LEAVES', name: 'Birkenlaub', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_SAPLING', name: 'Birkensetzling', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_STAIRS', name: 'Birkentreppe', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_SLAB', name: 'Birkenstufe', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_FENCE', name: 'Birkenzaun', group: 'Birke', category: 'Holz' },
  { id: 'BIRCH_DOOR', name: 'Birkentür', group: 'Birke', category: 'Holz' },
  // --- Fichte ---
  { id: 'SPRUCE_LOG', name: 'Fichtenstamm', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_WOOD', name: 'Fichtenholz', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_PLANKS', name: 'Fichtenbretter', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_LEAVES', name: 'Fichtenlaub', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_SAPLING', name: 'Fichtensetzling', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_STAIRS', name: 'Fichtentreppe', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_SLAB', name: 'Fichtenstufe', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_FENCE', name: 'Fichtenzaun', group: 'Fichte', category: 'Holz' },
  { id: 'SPRUCE_DOOR', name: 'Fichtentür', group: 'Fichte', category: 'Holz' },
  // --- Dschungelbaum ---
  { id: 'JUNGLE_LOG', name: 'Dschungelholzstamm', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_WOOD', name: 'Dschungelholz', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_PLANKS', name: 'Dschungelbretter', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_LEAVES', name: 'Dschungellaub', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_SAPLING', name: 'Dschungelsetzling', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_STAIRS', name: 'Dschungeltreppe', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_SLAB', name: 'Dschungelstufe', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_FENCE', name: 'Dschungelzaun', group: 'Dschungelbaum', category: 'Holz' },
  { id: 'JUNGLE_DOOR', name: 'Dschungeltür', group: 'Dschungelbaum', category: 'Holz' },
  // --- Akazie ---
  { id: 'ACACIA_LOG', name: 'Akazienstamm', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_WOOD', name: 'Akazienholz', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_PLANKS', name: 'Akazienbretter', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_LEAVES', name: 'Akazienlaub', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_SAPLING', name: 'Akaziensetzling', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_STAIRS', name: 'Akazientreppe', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_SLAB', name: 'Akazienstufe', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_FENCE', name: 'Akazienzaun', group: 'Akazie', category: 'Holz' },
  { id: 'ACACIA_DOOR', name: 'Akazientür', group: 'Akazie', category: 'Holz' },
  // --- Dunkeleiche ---
  { id: 'DARK_OAK_LOG', name: 'Dunkeleichenstamm', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_WOOD', name: 'Dunkeleichenholz', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_PLANKS', name: 'Dunkeleichenbretter', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_LEAVES', name: 'Dunkeleichenlaub', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_SAPLING', name: 'Dunkeleichensetzling', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_STAIRS', name: 'Dunkeleichentreppe', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_SLAB', name: 'Dunkeleichenstufe', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_FENCE', name: 'Dunkeleichenzaun', group: 'Dunkeleiche', category: 'Holz' },
  { id: 'DARK_OAK_DOOR', name: 'Dunkeleichentür', group: 'Dunkeleiche', category: 'Holz' },
  // --- Mangrove ---
  { id: 'MANGROVE_LOG', name: 'Mangrovenstamm', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_WOOD', name: 'Mangrovenholz', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_PLANKS', name: 'Mangrovenbretter', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_LEAVES', name: 'Mangrovenlaub', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_PROPAGULE', name: 'Mangrovenpropagule', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_STAIRS', name: 'Mangrooventreppe', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_SLAB', name: 'Mangrovenstufe', group: 'Mangrove', category: 'Holz' },
  { id: 'MANGROVE_ROOTS', name: 'Mangrovenwurzeln', group: 'Mangrove', category: 'Holz' },
  // --- Kirsche ---
  { id: 'CHERRY_LOG', name: 'Kirschstamm', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_WOOD', name: 'Kirschholz', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_PLANKS', name: 'Kirschbretter', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_LEAVES', name: 'Kirschlaub', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_SAPLING', name: 'Kirschsetzling', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_STAIRS', name: 'Kirschtreppe', group: 'Kirsche', category: 'Holz' },
  { id: 'CHERRY_SLAB', name: 'Kirschstufe', group: 'Kirsche', category: 'Holz' },
  // --- Bambus ---
  { id: 'BAMBOO_BLOCK', name: 'Bambusblock', group: 'Bambus', category: 'Holz' },
  { id: 'BAMBOO_PLANKS', name: 'Bambusbretter', group: 'Bambus', category: 'Holz' },
  { id: 'BAMBOO', name: 'Bambus', group: 'Bambus', category: 'Holz' },
  { id: 'BAMBOO_MOSAIC', name: 'Bambusmosaik', group: 'Bambus', category: 'Holz' },
  // --- Pilzholz (Nether) ---
  { id: 'CRIMSON_STEM', name: 'Karmesinstamm', group: 'Pilzholz', category: 'Holz' },
  { id: 'CRIMSON_PLANKS', name: 'Karmesinbretter', group: 'Pilzholz', category: 'Holz' },
  { id: 'CRIMSON_FUNGUS', name: 'Karmesinpilz', group: 'Pilzholz', category: 'Holz' },
  { id: 'WARPED_STEM', name: 'Wirrstamm', group: 'Pilzholz', category: 'Holz' },
  { id: 'WARPED_PLANKS', name: 'Wirrbretter', group: 'Pilzholz', category: 'Holz' },
  { id: 'WARPED_FUNGUS', name: 'Wirrpilz', group: 'Pilzholz', category: 'Holz' },

  // ===================== STEIN & ERDEN =====================
  // --- Stein ---
  { id: 'STONE', name: 'Stein', group: 'Stein', category: 'Stein & Erden' },
  { id: 'COBBLESTONE', name: 'Bruchstein', group: 'Stein', category: 'Stein & Erden' },
  { id: 'MOSSY_COBBLESTONE', name: 'Bemooster Bruchstein', group: 'Stein', category: 'Stein & Erden' },
  { id: 'STONE_BRICKS', name: 'Steinziegel', group: 'Stein', category: 'Stein & Erden' },
  { id: 'MOSSY_STONE_BRICKS', name: 'Bemooste Steinziegel', group: 'Stein', category: 'Stein & Erden' },
  { id: 'CRACKED_STONE_BRICKS', name: 'Rissige Steinziegel', group: 'Stein', category: 'Stein & Erden' },
  { id: 'CHISELED_STONE_BRICKS', name: 'Gemeißelte Steinziegel', group: 'Stein', category: 'Stein & Erden' },
  { id: 'STONE_STAIRS', name: 'Steintreppe', group: 'Stein', category: 'Stein & Erden' },
  { id: 'STONE_SLAB', name: 'Steinstufe', group: 'Stein', category: 'Stein & Erden' },
  { id: 'SMOOTH_STONE', name: 'Glatter Stein', group: 'Stein', category: 'Stein & Erden' },
  // --- Tiefenschiefer ---
  { id: 'DEEPSLATE', name: 'Tiefenschiefer', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'COBBLED_DEEPSLATE', name: 'Tiefenschieferbruchstein', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'DEEPSLATE_BRICKS', name: 'Tiefenschieferziegel', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'DEEPSLATE_TILES', name: 'Tiefenschieferfliesen', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'CHISELED_DEEPSLATE', name: 'Gemeißelter Tiefenschiefer', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'POLISHED_DEEPSLATE', name: 'Polierter Tiefenschiefer', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'CRACKED_DEEPSLATE_BRICKS', name: 'Rissige Tiefenschieferziegel', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  { id: 'CRACKED_DEEPSLATE_TILES', name: 'Rissige Tiefenschieferfliesen', group: 'Tiefenschiefer', category: 'Stein & Erden' },
  // --- Granit/Diorit/Andesit ---
  { id: 'GRANITE', name: 'Granit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'POLISHED_GRANITE', name: 'Polierter Granit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'DIORITE', name: 'Diorit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'POLISHED_DIORITE', name: 'Polierter Diorit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'ANDESITE', name: 'Andesit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'POLISHED_ANDESITE', name: 'Polierter Andesit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'TUFF', name: 'Tuffstein', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'CALCITE', name: 'Calcit', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  { id: 'DRIPSTONE_BLOCK', name: 'Tropfsteinblock', group: 'Granit, Diorit & Andesit', category: 'Stein & Erden' },
  // --- Sandstein ---
  { id: 'SANDSTONE', name: 'Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  { id: 'CHISELED_SANDSTONE', name: 'Gemeißelter Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  { id: 'SMOOTH_SANDSTONE', name: 'Glatter Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  { id: 'RED_SANDSTONE', name: 'Roter Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  { id: 'CHISELED_RED_SANDSTONE', name: 'Gemeißelter roter Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  { id: 'SMOOTH_RED_SANDSTONE', name: 'Glatter roter Sandstein', group: 'Sandstein', category: 'Stein & Erden' },
  // --- Erde, Gras, Kies, Sand ---
  { id: 'DIRT', name: 'Erde', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'GRASS_BLOCK', name: 'Grasblock', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'COARSE_DIRT', name: 'Grobe Erde', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'PODZOL', name: 'Podsol', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'ROOTED_DIRT', name: 'Verwurzelte Erde', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'GRAVEL', name: 'Kies', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'SAND', name: 'Sand', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'RED_SAND', name: 'Roter Sand', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'SUSPICIOUS_SAND', name: 'Verdächtiger Sand', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  { id: 'SUSPICIOUS_GRAVEL', name: 'Verdächtiger Kies', group: 'Erde, Gras & Sand', category: 'Stein & Erden' },
  // --- Ton & Terrakotta ---
  { id: 'CLAY', name: 'Lehmblock', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'TERRACOTTA', name: 'Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'WHITE_TERRACOTTA', name: 'Weiße Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'ORANGE_TERRACOTTA', name: 'Orangene Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'RED_TERRACOTTA', name: 'Rote Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'BROWN_TERRACOTTA', name: 'Braune Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  { id: 'GLAZED_TERRACOTTA', name: 'Glasierte Terrakotta', group: 'Ton & Terrakotta', category: 'Stein & Erden' },
  // --- Schlamm ---
  { id: 'MUD', name: 'Schlamm', group: 'Schlamm', category: 'Stein & Erden' },
  { id: 'PACKED_MUD', name: 'Festgepackter Schlamm', group: 'Schlamm', category: 'Stein & Erden' },
  { id: 'MUD_BRICKS', name: 'Schlammziegel', group: 'Schlamm', category: 'Stein & Erden' },

  // ===================== ERZE & EDELSTEINE =====================
  { id: 'COAL_ORE', name: 'Kohleerz', group: 'Kohle', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_COAL_ORE', name: 'Tiefenschiefer-Kohleerz', group: 'Kohle', category: 'Erze & Edelsteine' },
  { id: 'COAL_BLOCK', name: 'Kohleblock', group: 'Kohle', category: 'Erze & Edelsteine' },

  { id: 'IRON_ORE', name: 'Eisenerz', group: 'Eisen', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_IRON_ORE', name: 'Tiefenschiefer-Eisenerz', group: 'Eisen', category: 'Erze & Edelsteine' },
  { id: 'IRON_BLOCK', name: 'Eisenblock', group: 'Eisen', category: 'Erze & Edelsteine' },
  { id: 'RAW_IRON_BLOCK', name: 'Rohes Eisenblock', group: 'Eisen', category: 'Erze & Edelsteine' },

  { id: 'COPPER_ORE', name: 'Kupfererz', group: 'Kupfer', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_COPPER_ORE', name: 'Tiefenschiefer-Kupfererz', group: 'Kupfer', category: 'Erze & Edelsteine' },
  { id: 'COPPER_BLOCK', name: 'Kupferblock', group: 'Kupfer', category: 'Erze & Edelsteine' },
  { id: 'RAW_COPPER_BLOCK', name: 'Rohes Kupferblock', group: 'Kupfer', category: 'Erze & Edelsteine' },
  { id: 'CUT_COPPER', name: 'Geschnittenes Kupfer', group: 'Kupfer', category: 'Erze & Edelsteine' },
  { id: 'OXIDIZED_COPPER', name: 'Oxidiertes Kupfer', group: 'Kupfer', category: 'Erze & Edelsteine' },

  { id: 'GOLD_ORE', name: 'Golderz', group: 'Gold', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_GOLD_ORE', name: 'Tiefenschiefer-Golderz', group: 'Gold', category: 'Erze & Edelsteine' },
  { id: 'NETHER_GOLD_ORE', name: 'Nether-Golderz', group: 'Gold', category: 'Erze & Edelsteine' },
  { id: 'GOLD_BLOCK', name: 'Goldblock', group: 'Gold', category: 'Erze & Edelsteine' },
  { id: 'RAW_GOLD_BLOCK', name: 'Rohes Goldblock', group: 'Gold', category: 'Erze & Edelsteine' },

  { id: 'REDSTONE_ORE', name: 'Redstone-Erz', group: 'Redstone', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_REDSTONE_ORE', name: 'Tiefenschiefer-Redstone-Erz', group: 'Redstone', category: 'Erze & Edelsteine' },
  { id: 'REDSTONE_BLOCK', name: 'Redstoneblock', group: 'Redstone', category: 'Erze & Edelsteine' },

  { id: 'LAPIS_ORE', name: 'Lapislazulierz', group: 'Lapislazuli', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_LAPIS_ORE', name: 'Tiefenschiefer-Lapislazulierz', group: 'Lapislazuli', category: 'Erze & Edelsteine' },
  { id: 'LAPIS_BLOCK', name: 'Lapislazuliblock', group: 'Lapislazuli', category: 'Erze & Edelsteine' },

  { id: 'DIAMOND_ORE', name: 'Diamanterz', group: 'Diamant', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_DIAMOND_ORE', name: 'Tiefenschiefer-Diamanterz', group: 'Diamant', category: 'Erze & Edelsteine' },
  { id: 'DIAMOND_BLOCK', name: 'Diamantblock', group: 'Diamant', category: 'Erze & Edelsteine' },

  { id: 'EMERALD_ORE', name: 'Smaragderz', group: 'Smaragd', category: 'Erze & Edelsteine' },
  { id: 'DEEPSLATE_EMERALD_ORE', name: 'Tiefenschiefer-Smaragderz', group: 'Smaragd', category: 'Erze & Edelsteine' },
  { id: 'EMERALD_BLOCK', name: 'Smaragdblock', group: 'Smaragd', category: 'Erze & Edelsteine' },

  { id: 'ANCIENT_DEBRIS', name: 'Antiker Schutt', group: 'Netherit', category: 'Erze & Edelsteine' },
  { id: 'NETHERITE_BLOCK', name: 'Netheritblock', group: 'Netherit', category: 'Erze & Edelsteine' },

  // ===================== NATUR & PFLANZEN =====================
  { id: 'AZALEA_LEAVES', name: 'Azaleenlaub', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'FLOWERING_AZALEA_LEAVES', name: 'Blühendes Azaleenlaub', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'VINE', name: 'Ranken', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'MOSS_BLOCK', name: 'Moosblock', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'MOSS_CARPET', name: 'Moosteppich', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'HANGING_ROOTS', name: 'Hängende Wurzeln', group: 'Blätter & Büsche', category: 'Natur & Pflanzen' },
  { id: 'SHORT_GRASS', name: 'Gras', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'TALL_GRASS', name: 'Hohes Gras', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'FERN', name: 'Farn', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'LARGE_FERN', name: 'Großer Farn', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'DEAD_BUSH', name: 'Totes Gestrüpp', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'SWEET_BERRY_BUSH', name: 'Süßbeerenstrauch', group: 'Gräser & Büsche', category: 'Natur & Pflanzen' },
  { id: 'DANDELION', name: 'Löwenzahn', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'POPPY', name: 'Mohnblume', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'BLUE_ORCHID', name: 'Blaue Orchidee', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'ALLIUM', name: 'Lauch', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'AZURE_BLUET', name: 'Porzellansternchen', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'TULIP', name: 'Tulpe', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'OXEYE_DAISY', name: 'Margerite', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'CORNFLOWER', name: 'Kornblume', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'LILY_OF_THE_VALLEY', name: 'Maiglöckchen', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'SUNFLOWER', name: 'Sonnenblume', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'LILAC', name: 'Flieder', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'ROSE_BUSH', name: 'Rosenstrauch', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'PEONY', name: 'Pfingstrose', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'WITHER_ROSE', name: 'Witherrose', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'PITCHER_PLANT', name: 'Kannenpflanze', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'TORCHFLOWER', name: 'Fackellilie', group: 'Blumen', category: 'Natur & Pflanzen' },
  { id: 'BROWN_MUSHROOM', name: 'Braune Pilze', group: 'Pilze', category: 'Natur & Pflanzen' },
  { id: 'RED_MUSHROOM', name: 'Rote Pilze', group: 'Pilze', category: 'Natur & Pflanzen' },
  { id: 'MUSHROOM_STEM', name: 'Pilzstiel', group: 'Pilze', category: 'Natur & Pflanzen' },
  { id: 'CACTUS', name: 'Kaktus', group: 'Kaktus', category: 'Natur & Pflanzen' },
  { id: 'CACTUS_FLOWER', name: 'Kaktusblüte', group: 'Kaktus', category: 'Natur & Pflanzen' },
  { id: 'WHEAT', name: 'Weizen', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'CARROTS', name: 'Karotten', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'POTATOES', name: 'Kartoffeln', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'BEETROOTS', name: 'Rote Bete', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'MELON', name: 'Melone', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'PUMPKIN', name: 'Kürbis', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'SUGAR_CANE', name: 'Zuckerrohr', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'COCOA', name: 'Kakao', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'NETHER_WART', name: 'Netherwarze', group: 'Feldfrüchte', category: 'Natur & Pflanzen' },
  { id: 'SEAGRASS', name: 'Seegras', group: 'Wasserpflanzen', category: 'Natur & Pflanzen' },
  { id: 'KELP', name: 'Seetang', group: 'Wasserpflanzen', category: 'Natur & Pflanzen' },
  { id: 'SEA_PICKLE', name: 'Seegurke', group: 'Wasserpflanzen', category: 'Natur & Pflanzen' },
  { id: 'LILY_PAD', name: 'Seerosenblatt', group: 'Wasserpflanzen', category: 'Natur & Pflanzen' },
  { id: 'BIG_DRIPLEAF', name: 'Großes Tropfblatt', group: 'Höhlenpflanzen', category: 'Natur & Pflanzen' },
  { id: 'SMALL_DRIPLEAF', name: 'Kleines Tropfblatt', group: 'Höhlenpflanzen', category: 'Natur & Pflanzen' },
  { id: 'SPORE_BLOSSOM', name: 'Sporenblüte', group: 'Höhlenpflanzen', category: 'Natur & Pflanzen' },
  { id: 'GLOW_LICHEN', name: 'Leuchtflechte', group: 'Höhlenpflanzen', category: 'Natur & Pflanzen' },
  { id: 'PINK_PETALS', name: 'Rosa Blütenblätter', group: 'Höhlenpflanzen', category: 'Natur & Pflanzen' },
  { id: 'ICE', name: 'Eis', group: 'Eis & Schnee', category: 'Natur & Pflanzen' },
  { id: 'PACKED_ICE', name: 'Packeis', group: 'Eis & Schnee', category: 'Natur & Pflanzen' },
  { id: 'BLUE_ICE', name: 'Blaues Eis', group: 'Eis & Schnee', category: 'Natur & Pflanzen' },
  { id: 'SNOW', name: 'Schnee', group: 'Eis & Schnee', category: 'Natur & Pflanzen' },
  { id: 'SNOW_BLOCK', name: 'Schneeblock', group: 'Eis & Schnee', category: 'Natur & Pflanzen' },
  { id: 'OBSIDIAN', name: 'Obsidian', group: 'Sonstige Naturblöcke', category: 'Natur & Pflanzen' },
  { id: 'CRYING_OBSIDIAN', name: 'Weinender Obsidian', group: 'Sonstige Naturblöcke', category: 'Natur & Pflanzen' },
  { id: 'MAGMA_BLOCK', name: 'Magmablock', group: 'Sonstige Naturblöcke', category: 'Natur & Pflanzen' },
  { id: 'HONEY_BLOCK', name: 'Honigblock', group: 'Sonstige Naturblöcke', category: 'Natur & Pflanzen' },
  { id: 'HONEYCOMB_BLOCK', name: 'Wabenblock', group: 'Sonstige Naturblöcke', category: 'Natur & Pflanzen' },
  { id: 'SCULK', name: 'Sculk', group: 'Sculk', category: 'Natur & Pflanzen' },
  { id: 'SCULK_CATALYST', name: 'Sculk-Katalysator', group: 'Sculk', category: 'Natur & Pflanzen' },
  { id: 'SCULK_VEIN', name: 'Sculk-Ader', group: 'Sculk', category: 'Natur & Pflanzen' },
  { id: 'SCULK_SENSOR', name: 'Sculk-Sensor', group: 'Sculk', category: 'Natur & Pflanzen' },
  { id: 'SCULK_SHRIEKER', name: 'Sculk-Schreier', group: 'Sculk', category: 'Natur & Pflanzen' },

  // ===================== NETHER =====================
  { id: 'NETHERRACK', name: 'Netherrack', group: 'Netherrack', category: 'Nether' },
  { id: 'NETHER_BRICKS', name: 'Netherziegel', group: 'Netherrack', category: 'Nether' },
  { id: 'CRACKED_NETHER_BRICKS', name: 'Rissige Netherziegel', group: 'Netherrack', category: 'Nether' },
  { id: 'CHISELED_NETHER_BRICKS', name: 'Gemeißelte Netherziegel', group: 'Netherrack', category: 'Nether' },
  { id: 'RED_NETHER_BRICKS', name: 'Rote Netherziegel', group: 'Netherrack', category: 'Nether' },
  { id: 'SOUL_SAND', name: 'Seelensand', group: 'Seelensand & -boden', category: 'Nether' },
  { id: 'SOUL_SOIL', name: 'Seelenboden', group: 'Seelensand & -boden', category: 'Nether' },
  { id: 'BASALT', name: 'Basalt', group: 'Basalt', category: 'Nether' },
  { id: 'POLISHED_BASALT', name: 'Polierter Basalt', group: 'Basalt', category: 'Nether' },
  { id: 'SMOOTH_BASALT', name: 'Glatter Basalt', group: 'Basalt', category: 'Nether' },
  { id: 'BLACKSTONE', name: 'Schwarzstein', group: 'Schwarzstein', category: 'Nether' },
  { id: 'POLISHED_BLACKSTONE', name: 'Polierter Schwarzstein', group: 'Schwarzstein', category: 'Nether' },
  { id: 'GILDED_BLACKSTONE', name: 'Vergoldeter Schwarzstein', group: 'Schwarzstein', category: 'Nether' },
  { id: 'CHISELED_POLISHED_BLACKSTONE', name: 'Gemeißelter Schwarzstein', group: 'Schwarzstein', category: 'Nether' },
  { id: 'QUARTZ_BLOCK', name: 'Netherquarzblock', group: 'Quarz', category: 'Nether' },
  { id: 'CHISELED_QUARTZ_BLOCK', name: 'Gemeißelter Quarzblock', group: 'Quarz', category: 'Nether' },
  { id: 'QUARTZ_PILLAR', name: 'Quarzsäule', group: 'Quarz', category: 'Nether' },
  { id: 'SMOOTH_QUARTZ', name: 'Glatter Quarzblock', group: 'Quarz', category: 'Nether' },
  { id: 'NETHER_QUARTZ_ORE', name: 'Netherquarzerz', group: 'Quarz', category: 'Nether' },
  { id: 'GLOWSTONE', name: 'Leuchtstein', group: 'Lichtblöcke', category: 'Nether' },
  { id: 'SHROOMLIGHT', name: 'Pilzlicht', group: 'Lichtblöcke', category: 'Nether' },
  { id: 'NETHER_WART_BLOCK', name: 'Netherwarzenblock', group: 'Sonstiges Nether', category: 'Nether' },
  { id: 'WARPED_WART_BLOCK', name: 'Wirrwarzenblock', group: 'Sonstiges Nether', category: 'Nether' },
  { id: 'NETHER_SPROUTS', name: 'Nethersprossen', group: 'Sonstiges Nether', category: 'Nether' },
  { id: 'WEEPING_VINES', name: 'Weinende Ranken', group: 'Sonstiges Nether', category: 'Nether' },
  { id: 'TWISTING_VINES', name: 'Wirrranken', group: 'Sonstiges Nether', category: 'Nether' },

  // ===================== END =====================
  { id: 'END_STONE', name: 'Endstein', group: 'Endstein', category: 'End' },
  { id: 'END_STONE_BRICKS', name: 'Endsteinziegel', group: 'Endstein', category: 'End' },
  { id: 'PURPUR_BLOCK', name: 'Purpurblock', group: 'Purpur', category: 'End' },
  { id: 'PURPUR_PILLAR', name: 'Purpursäule', group: 'Purpur', category: 'End' },
  { id: 'PURPUR_STAIRS', name: 'Purpurtreppe', group: 'Purpur', category: 'End' },
  { id: 'CHORUS_PLANT', name: 'Chorusgewächs', group: 'Chorus', category: 'End' },
  { id: 'CHORUS_FLOWER', name: 'Chorusblüte', group: 'Chorus', category: 'End' },

  // ===================== SONSTIGES =====================
  { id: 'GLASS', name: 'Glas', group: 'Glas', category: 'Sonstiges' },
  { id: 'TINTED_GLASS', name: 'Getöntes Glas', group: 'Glas', category: 'Sonstiges' },
  { id: 'WHITE_STAINED_GLASS', name: 'Weißes Glas', group: 'Glas', category: 'Sonstiges' },
  { id: 'WHITE_WOOL', name: 'Weiße Wolle', group: 'Wolle & Teppich', category: 'Sonstiges' },
  { id: 'RED_WOOL', name: 'Rote Wolle', group: 'Wolle & Teppich', category: 'Sonstiges' },
  { id: 'WHITE_CARPET', name: 'Weißer Teppich', group: 'Wolle & Teppich', category: 'Sonstiges' },
  { id: 'BOOKSHELF', name: 'Bücherregal', group: 'Dekoration', category: 'Sonstiges' },
  { id: 'CHISELED_BOOKSHELF', name: 'Gemeißeltes Bücherregal', group: 'Dekoration', category: 'Sonstiges' },
  { id: 'BRICKS', name: 'Ziegel', group: 'Dekoration', category: 'Sonstiges' },
  { id: 'COBWEB', name: 'Spinnennetz', group: 'Dekoration', category: 'Sonstiges' },
  { id: 'CHEST', name: 'Truhe', group: 'Funktional', category: 'Sonstiges' },
  { id: 'TRAPPED_CHEST', name: 'Fallentruhe', group: 'Funktional', category: 'Sonstiges' },
  { id: 'BARREL', name: 'Fass', group: 'Funktional', category: 'Sonstiges' },
  { id: 'FURNACE', name: 'Ofen', group: 'Funktional', category: 'Sonstiges' },
  { id: 'BLAST_FURNACE', name: 'Schmelzofen', group: 'Funktional', category: 'Sonstiges' },
  { id: 'SMOKER', name: 'Räucherofen', group: 'Funktional', category: 'Sonstiges' },
  { id: 'CRAFTING_TABLE', name: 'Werkbank', group: 'Funktional', category: 'Sonstiges' },
  { id: 'ANVIL', name: 'Amboss', group: 'Funktional', category: 'Sonstiges' },
  { id: 'ENCHANTING_TABLE', name: 'Zaubertisch', group: 'Funktional', category: 'Sonstiges' },
  { id: 'BREWING_STAND', name: 'Braustand', group: 'Funktional', category: 'Sonstiges' },
  { id: 'CAULDRON', name: 'Kessel', group: 'Funktional', category: 'Sonstiges' },
  { id: 'LOOM', name: 'Webstuhl', group: 'Funktional', category: 'Sonstiges' },
  { id: 'STONECUTTER', name: 'Steinsäge', group: 'Funktional', category: 'Sonstiges' },
  { id: 'SMITHING_TABLE', name: 'Schmiedetisch', group: 'Funktional', category: 'Sonstiges' },
  { id: 'CARTOGRAPHY_TABLE', name: 'Kartentisch', group: 'Funktional', category: 'Sonstiges' },
  { id: 'FLETCHING_TABLE', name: 'Pfeilmachertisch', group: 'Funktional', category: 'Sonstiges' },
  { id: 'COMPOSTER', name: 'Komposter', group: 'Funktional', category: 'Sonstiges' },
  { id: 'LECTERN', name: 'Lesepult', group: 'Funktional', category: 'Sonstiges' },
  { id: 'BEACON', name: 'Leuchtfeuer', group: 'Funktional', category: 'Sonstiges' },
  { id: 'CONDUIT', name: 'Aquakulturschrein', group: 'Funktional', category: 'Sonstiges' },
  { id: 'LODESTONE', name: 'Leitstein', group: 'Funktional', category: 'Sonstiges' },
  { id: 'REDSTONE_LAMP', name: 'Redstonelampe', group: 'Redstone-Komponenten', category: 'Sonstiges' },
  { id: 'PISTON', name: 'Kolben', group: 'Redstone-Komponenten', category: 'Sonstiges' },
  { id: 'OBSERVER', name: 'Beobachter', group: 'Redstone-Komponenten', category: 'Sonstiges' },
  { id: 'TARGET', name: 'Zielblock', group: 'Redstone-Komponenten', category: 'Sonstiges' },
  { id: 'TNT', name: 'TNT', group: 'Redstone-Komponenten', category: 'Sonstiges' },
  { id: 'LADDER', name: 'Leiter', group: 'Funktional', category: 'Sonstiges' },
  { id: 'SCAFFOLDING', name: 'Gerüst', group: 'Funktional', category: 'Sonstiges' },
  { id: 'HAY_BLOCK', name: 'Heuballen', group: 'Sonstiges Material', category: 'Sonstiges' },
  { id: 'BONE_BLOCK', name: 'Knochenblock', group: 'Sonstiges Material', category: 'Sonstiges' },
  { id: 'SLIME_BLOCK', name: 'Schleimblock', group: 'Sonstiges Material', category: 'Sonstiges' },
  { id: 'AMETHYST_BLOCK', name: 'Amethystblock', group: 'Sonstiges Material', category: 'Sonstiges' },
  { id: 'BUDDING_AMETHYST', name: 'Knospender Amethystblock', group: 'Sonstiges Material', category: 'Sonstiges' },
  { id: 'SPONGE', name: 'Schwamm', group: 'Sonstiges Material', category: 'Sonstiges' },
]

export const BLOCK_CATEGORIES: BlockCategory[] = ['Holz', 'Stein & Erden', 'Erze & Edelsteine', 'Natur & Pflanzen', 'Nether', 'End', 'Sonstiges']

export function getBlockById(id: string): BlockEntry | undefined {
  return ALL_BLOCKS.find(b => b.id === id)
}

// Liefert alle Materialgruppen-Namen innerhalb einer Kategorie, in der
// Reihenfolge, in der sie zuerst in ALL_BLOCKS auftauchen.
export function getGroupsInCategory(category: BlockCategory): string[] {
  const groups: string[] = []
  for (const block of ALL_BLOCKS) {
    if (block.category === category && !groups.includes(block.group)) {
      groups.push(block.group)
    }
  }
  return groups
}

// Liefert alle Blöcke innerhalb einer Materialgruppe.
export function getBlocksInGroup(category: BlockCategory, group: string): BlockEntry[] {
  return ALL_BLOCKS.filter(b => b.category === category && b.group === group)
}